# Generated by Django 4.2.11 on 2024-03-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('name', 'user')},
        ),
    ]
